import data from "./agents.json";

/**
 * ============================================================================
 * THE AGENCY — every agent from msitarzewski/agency-agents, as data
 * ============================================================================
 *
 * `agents.json` is generated by `npm run sync:agency` (scripts/sync-agency.mjs)
 * and is never edited by hand. This module gives it types and the handful of
 * helpers the dashboard at /agency needs: lookup by slug, filtering, sorting,
 * and the initials each agent is engraved with.
 *
 * Two upstream fields are carried but never rendered — `emoji` and `color` —
 * because the house rules ban emoji on sight and allow colour only through
 * lib/design/tokens.ts. They are kept so the file stays a faithful record of
 * the source, and so a future feature can decide for itself.
 */

export interface AgencyService {
  name: string;
  url: string | null;
  tier: string | null;
}

export interface AgencyAgent {
  /** The upstream file stem — the id its runbooks use, so the id here too. */
  slug: string;
  /** The slug upstream's installers derive from the display name. */
  nameSlug: string;
  name: string;
  /** Top-level upstream directory, e.g. "engineering". */
  division: string;
  /** Second-level directory where one exists, e.g. "unity". */
  group: string | null;
  description: string;
  /** One-line personality, occasionally empty upstream. */
  vibe: string;
  tools: string[];
  author: string | null;
  services: AgencyService[];
  /** Upstream's avatar emoji. Carried, never rendered. */
  emoji: string;
  /** Upstream's colour hint (a name or a hex). Carried, never rendered. */
  color: string;
  /** The spec's `##` sections, emoji stripped. */
  headings: string[];
  /** Body length in words — a rough depth gauge. */
  words: number;
  path: string;
  sourceUrl: string;
}

export interface AgencyDivision {
  id: string;
  label: string;
  count: number;
}

export interface AgencyRunbookGroup {
  group: string;
  activation: string | null;
  /** Agent slugs; every one resolves to an entry in `agents`. */
  agents: string[];
}

export interface AgencyRunbook {
  slug: string;
  title: string;
  mode: string;
  duration: string;
  summary: string;
  docUrl: string | null;
  roster: AgencyRunbookGroup[];
}

export interface AgencyMeta {
  repo: string;
  repoUrl: string;
  license: string;
  commit: string | null;
  commitDate: string | null;
  syncedAt: string;
  agentCount: number;
  divisionCount: number;
}

export interface AgencyData {
  meta: AgencyMeta;
  divisions: AgencyDivision[];
  agents: AgencyAgent[];
  runbooks: AgencyRunbook[];
}

// The JSON's inferred literal types are narrower than the interfaces above
// (a field that happens to be null in every record infers as `null`), and they
// change with every sync. Going through `unknown` keeps that from ever being a
// type error; the sync script is what guarantees the shape.
export const AGENCY = data as unknown as AgencyData;

export const AGENTS: readonly AgencyAgent[] = AGENCY.agents;
export const DIVISIONS: readonly AgencyDivision[] = AGENCY.divisions;
export const RUNBOOKS: readonly AgencyRunbook[] = AGENCY.runbooks;
export const META: AgencyMeta = AGENCY.meta;

const BY_SLUG = new Map(AGENTS.map((a) => [a.slug, a]));
const DIVISION_LABEL = new Map(DIVISIONS.map((d) => [d.id, d.label]));
const DIVISION_ORDER = new Map(DIVISIONS.map((d, i) => [d.id, i]));

export function agentBySlug(slug: string | null | undefined): AgencyAgent | undefined {
  return slug ? BY_SLUG.get(slug) : undefined;
}

export function divisionLabel(id: string): string {
  return DIVISION_LABEL.get(id) ?? id;
}

/** "unity" → "Unity", "roblox-studio" → "Roblox Studio". */
export function groupLabel(group: string): string {
  return group
    .split("-")
    .map((w) => (w === "ios" ? "iOS" : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ");
}

export type AgencySort = "division" | "name" | "depth";

export const SORTS: { id: AgencySort; label: string }[] = [
  { id: "division", label: "By division" },
  { id: "name", label: "A to Z" },
  { id: "depth", label: "Longest spec first" },
];

/** Everything a search term may match, lower-cased and built once per agent. */
const SEARCH_TEXT = new Map<string, string>();
function searchText(a: AgencyAgent): string {
  let s = SEARCH_TEXT.get(a.slug);
  if (s === undefined) {
    s = [
      a.name,
      a.description,
      a.vibe,
      a.slug,
      divisionLabel(a.division),
      a.group ? groupLabel(a.group) : "",
      a.tools.join(" "),
      a.author ?? "",
    ]
      .join(" ")
      .toLowerCase();
    SEARCH_TEXT.set(a.slug, s);
  }
  return s;
}

export interface AgencyFilter {
  query: string;
  /** A division id, or null for every division. */
  division: string | null;
  sort: AgencySort;
}

/**
 * Filter and order the roster. Every whitespace-separated term in the query
 * must appear somewhere in the agent's text, so "unity shader" narrows the way
 * a person expects it to.
 */
export function filterAgents(list: readonly AgencyAgent[], f: AgencyFilter): AgencyAgent[] {
  const terms = f.query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  const out = list.filter((a) => {
    if (f.division && a.division !== f.division) return false;
    if (terms.length === 0) return true;
    const hay = searchText(a);
    return terms.every((t) => hay.includes(t));
  });

  const byName = (x: AgencyAgent, y: AgencyAgent) => x.name.localeCompare(y.name, "en");
  switch (f.sort) {
    case "name":
      out.sort(byName);
      break;
    case "depth":
      out.sort((x, y) => y.words - x.words || byName(x, y));
      break;
    default:
      out.sort(
        (x, y) =>
          (DIVISION_ORDER.get(x.division) ?? 99) - (DIVISION_ORDER.get(y.division) ?? 99) ||
          byName(x, y)
      );
  }
  return out;
}

/**
 * The two letters an agent is engraved with: the initials of its first two
 * meaningful words. "Frontend Developer" → FD, "X/Twitter Intelligence Analyst"
 * → XT, "SRE" → SR.
 */
export function initials(name: string): string {
  const words = name
    .split(/[^A-Za-z0-9]+/)
    .filter((w) => w && !/^(and|the|of|for|a|an|to|in)$/i.test(w));
  if (words.length === 0) return "–";
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[1][0]).toUpperCase();
}

/** Deterministic across server and client — no locale or time-zone surprises. */
export function formatCount(n: number): string {
  return n.toLocaleString("en-US");
}

export function formatDate(iso: string | null): string {
  if (!iso) return "unknown date";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "unknown date";
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}
